name: build ci norules

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  EXILED_Plugins: ${{ github.workspace }}/EXILED_Plugins/Plugins
  SCP_Files: ${{ github.workspace }}/EXILED_Plugins/References
  EXILED_PLUGIN_FILE: ${{ github.workspace }}/Compass/Compass.csproj
  REPOSITORY_WITH_PLUGINS: Fontape/SCP-SL-NoRules
  REPOSITORY_PLUGINS_BRANCH: main

jobs:
  build:
    runs-on: windows-latest

    steps:
    -
      name: disable compression
      run: git config --global core.compression 0
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Get plugins
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY_WITH_PLUGINS }}
        ssh-key: ${{ secrets.GIT_KEY_DEPLOY_NORULES }}
        ref: ${{ env.REPOSITORY_PLUGINS_BRANCH }}
        path: 'EXILED_Plugins'
    - 
       name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v1.7.2
    - 
       name: Setup Nuget
       uses: nuget/setup-nuget@v1
    - 
       name: Restore Packages
       run: nuget restore ${{ env.EXILED_PLUGIN_FILE }}
    - 
       name: Build
       run: dotnet build --configuration Release --no-restore ${{ env.EXILED_PLUGIN_FILE }}
    -
       name: test
       run: dotnet test --verbosity normal
    -
       name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
        name: plugin
        path: Compass/bin/Release
